sudo: required

matrix:
  include:
    - language: python
      python:
        - "3.6"
      env:
        - TOXENV=travis
      install:
        - pip install tox
      script:
        - tox
    - language: node_js
      node_js:
        - "8"
      install:
        - npm install --global mocha
      script:
        - cd jstests
        - mocha test
notifications:
  email: false
